### ISSUE TITLE
Async background scope

### ISSUE THREAD

**Issue by MaQy** [HangfireIO/Hangfire.Ninject#4]
Hi,

We found an issue when using the "InBackgroundScope" option. If you include async methods in the process, as the scope is stored in the thread, it gets lost in inner methods. We solved it by using AsyncLocal feature from .NET 4.6 to store the current scope (by modifying the source code of this library). That way, any resolution that happens inside the job scope gets the same instances.

I think it would be an interesting addition to this library or a change in the Hangfire core itself, but the problem is backward compatibility to previous framework versions.

Thanks.

**Comment by odinserj** [comment]
Good catch, @MaQy! Unfortunately, we can't simply bump the .NET dependency to 4.6. However, it's possible to implement the `AsyncLocal<T>` in 4.5 also. Please see https://github.com/HangfireIO/Hangfire/pull/675/files for reference. Would you like to create a PR to support this feature in Hangfire.Ninject that targets .NET Framework 4.5?

**Comment by Grepsy** [comment]
We've ran into the exact same issues today. What's the recommended way to handle this? We're targeting 4.6.

**Comment by iaingalloway** [comment]
We've also encountered this issue upon upgrading to Hangfire 1.7

**Comment by iaingalloway** [comment]
Anyone else encountering this issue can find an example of a potential fix at https://github.com/iaingalloway/Hangfire.Ninject

I'm not creating a pull request because, like MaQy above, I've fixed the problem by targeting .NET 4.6. It's possible to fix this problem without retargeting, but I think long-term it would be better fixed on JobActivatorScope.

**Comment by odinserj** [comment]
Fixed in https://github.com/HangfireIO/Hangfire.Ninject/commit/b665407d497327a676f3156d1e018e5f8a12daae, will be released with version 2.0.0.
