### ISSUE TITLE
System.MissingMethodException when task with Dependency is called

### ISSUE THREAD

**Issue by diegosiao** [HangfireIO/Hangfire.Ninject#6]
I configured thisn in Startup.Configuration method of my Web Application .NET 4.8 but keep receiving a **System.MissingMethodException** complaining about a not existing "parameterless constructor defined".

```
var kernel = new StandardKernel();
kernel.Bind<MessageTasks>().ToSelf();
kernel.Bind<IMessageRepository>().ToMethod(ctx => new MessageRepository(OracleConnectionFactory.CreateContext()));

GlobalConfiguration.Configuration.UseNinjectActivator(kernel);
```

What did I missed?

**Packages:**

Hangfire.AspNet (0.2.0)
Hangfire.Core (1.7.9)
Hangfire.Ninject (1.2.0)
Ninject (3.2.2)
Ninjec.Web.Common (3.2.0)

**Comment by odinserj** [comment]
If it's complaining about the `MessageTasks` class, try binding it with the `ToMethod` method as with the `IMessageRepository`.
